# Generated by Django 5.2.8 on 2025-11-13 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('features', models.JSONField(default=dict)),
                ('target', models.FloatField(blank=True, null=True)),
                ('label', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=64)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('tickers', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('freq', models.CharField(default='D', max_length=8)),
                ('source', models.CharField(default='FRED', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NewNLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nlp', to='core.newsarticle')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('yhat', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelartifact')),
            ],
            options={
                'unique_together': {('model', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obv', to='core.series')),
            ],
            options={
                'indexes': [models.Index(fields=['series', 'date'], name='core_observ_series__257904_idx')],
                'unique_together': {('series', 'date')},
            },
        ),
    ]
